# Generated by Django 5.2.17 on 2026-08-26 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
