# Generated by Django 5.2.17 on 2026-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_payment_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('FONEPAY', 'Fonepay')], max_length=30),
        ),
    ]
