# Generated by Django 6.0.7 on 2026-08-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('students', '0001_initial'),
        ('styles', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='one_current_enrollment_per_student'),
        ),
    ]
