# Generated by Django 6.0.7 on 2026-08-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_enrollment_one_current_enrollment_per_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
    ]
