# Generated by Django 5.2.17 on 2026-08-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='package_term',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('THREE_MONTH', '3-Month'), ('SIX_MONTH', '6-Month'), ('YEARLY', 'Yearly')], max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('FONEPAY', 'Fonepay')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='age_at_admission',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age at Admission'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth_bs',
            field=models.CharField(blank=True, max_length=20, verbose_name='Date of Birth (B.S.)'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_qualification',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_dance_styles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_institute',
            field=models.CharField(blank=True, max_length=180, verbose_name='Previous Institute'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_college',
            field=models.CharField(blank=True, max_length=180, verbose_name='Current School/College'),
        ),
        migrations.AddField(
            model_name='student',
            name='training_duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Training Duration'),
        ),
    ]
