# Generated by Django 5.2.17 on 2026-08-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_packagetimeslot'),
        ('students', '0004_enrollment_package_term_enrollment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='packages.packagetimeslot', verbose_name='Class Time'),
        ),
    ]
