# Generated by Django 5.2.17 on 2026-08-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_packagetimeslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagetimeslot',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveConstraint(
            model_name='packagetimeslot',
            name='unique_package_time_slot',
        ),
        migrations.RemoveField(
            model_name='packagetimeslot',
            name='day_of_week',
        ),
        migrations.AddConstraint(
            model_name='packagetimeslot',
            constraint=models.UniqueConstraint(fields=('package', 'start_time', 'end_time'), name='unique_package_time_slot'),
        ),
    ]
