# Generated by Django 6.0.7 on 2026-08-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('pay_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('MONTHLY', 'Monthly')], default='HOURLY', max_length=10, verbose_name='Pay Type')),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pay Rate')),
                ('max_student_capacity', models.PositiveIntegerField(default=0, verbose_name='Max Student Capacity')),
                ('assigned_styles', models.ManyToManyField(blank=True, related_name='teachers', to='styles.dancestyle', verbose_name='Assigned Dance Styles')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['full_name'],
            },
        ),
    ]
