# Generated by Django 5.2.17 on 2026-09-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacheravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='max_student_capacity',
        ),
        migrations.AddField(
            model_name='teacher',
            name='pay_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of total student fees paid to this teacher (e.g. 15 = 15%)', max_digits=5, verbose_name='Pay Percentage (%)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pay Rate'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pay_type',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('MONTHLY', 'Monthly'), ('PERCENTAGE', 'Percentage of Fee')], default='HOURLY', max_length=10, verbose_name='Pay Type'),
        ),
    ]
