# Generated by Django 6.0.7 on 2026-08-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanceStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Style Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color_tag', models.CharField(blank=True, help_text='Hex color code for UI grouping', max_length=7, verbose_name='Color Tag')),
            ],
            options={
                'verbose_name': 'Dance Style',
                'verbose_name_plural': 'Dance Styles',
                'ordering': ['name'],
            },
        ),
    ]
